build: qemu: disable virtiofsd
Bulding qemu failed with the following error. Temporary solve this by
disabling virtiofsd.

```
FAILED: tools/virtiofsd/virtiofsd.p/passthrough_ll.c.o
gcc -m64 -mcx16 -Itools/virtiofsd/virtiofsd.p -Itools/virtiofsd -I../tools/virtiofsd -Isubprojects/libvhost-user -I../subprojects/libvhost-user -I. -Iqapi -Itrace -Iui -Iui/
shader -I/nix/store/hk5ciciwp0xy01znmk5xihkfjdkzhphh-libseccomp-2.5.4-dev/include -I/nix/store/br1qlnvr4n81zwvq830c1xvb90kyaspi-glib-2.74.3-dev/include -I/nix/store/br1qlnvr
4n81zwvq830c1xvb90kyaspi-glib-2.74.3-dev/include/glib-2.0 -I/nix/store/a87jrxjzq43y1050drrhs2yrbs5zj2na-glib-2.74.3/lib/glib-2.0/include -fdiagnostics-color=auto -Wall -Winv
alid-pch -std=gnu11 -O2 -g -isystem /scratch/masa/sev/AMDESE_local/linux-svsm/scripts/qemu/linux-headers -isystem linux-headers -iquote . -iquote /scratch/masa/sev/AMDESE_lo
cal/linux-svsm/scripts/qemu -iquote /scratch/masa/sev/AMDESE_local/linux-svsm/scripts/qemu/include -iquote /scratch/masa/sev/AMDESE_local/linux-svsm/scripts/qemu/disas/libvi
xl -iquote /scratch/masa/sev/AMDESE_local/linux-svsm/scripts/qemu/tcg/i386 -pthread -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_S
OURCE -Wstrict-prototypes -Wredundant-decls -Wundef -Wwrite-strings -Wmissing-prototypes -fno-strict-aliasing -fno-common -fwrapv -Wold-style-declaration -Wold-style-definit
ion -Wtype-limits -Wformat-security -Wformat-y2k -Winit-self -Wignored-qualifiers -Wempty-body -Wnested-externs -Wendif-labels -Wexpansion-to-defined -Wimplicit-fallthrough=
2 -Wno-missing-include-dirs -Wno-shift-negative-value -Wno-psabi -fstack-protector-strong -fPIE -MD -MQ tools/virtiofsd/virtiofsd.p/passthrough_ll.c.o -MF tools/virtiofsd/vi
rtiofsd.p/passthrough_ll.c.o.d -o tools/virtiofsd/virtiofsd.p/passthrough_ll.c.o -c ../tools/virtiofsd/passthrough_ll.c
../tools/virtiofsd/passthrough_ll.c: In function ‘do_statx’:
../tools/virtiofsd/passthrough_ll.c:982:36: error: ‘struct statx’ has no member named ‘stx_mnt_id’; did you mean ‘stx_uid’?
  982 |                 *mnt_id = statxbuf.stx_mnt_id;
      |                                    ^~~~~~~~~~
      |                                    stx_uid
```